// lab02-Angular-UI/src/app/video/video-list/video-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

export class Video {
  title: string;
  url: string;
  status: string;
  approved: boolean;
  likes: number;
  unlike: number;
  currentStatus: string;
  exitplayprogress: number;
}

@Component({
  selector: 'app-video-list',
  templateUrl: './video-list.component.html',
  styleUrls: ['./video-list.component.css']
})
export class VideoListComponent {

  @Input() videos: Video;

  @Output() addVideo = new EventEmitter<boolean>();


  constructor() {
  }

  loadVideoAddComponent() {
    this.addVideo.emit(true);
 }




}

<div class="container-fluid">
  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th scope="col"><button type="button" (click)="loadVideoAddComponent()" class="btn btn-dark">
          <fa-icon [icon]="['fas', 'plus']"></fa-icon>
        </button></th>
        <th scope="col" style="text-align: start">Title</th>
        <th scope="col" style="text-align: start">URL</th>
        <th scope="col">Action</th>
        <th scope="col">Like</th>
        <th scope="col">Unlike</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let video of videos">
        <th scope="row" class="col-sm-1">{{ video.id }}</th>
        <td class="col-sm-3" style="text-align: start">{{ video.title }}</td>
        <td class="col-sm-4" style="text-align: start">{{ video.url }}</td>
        <td>
          <button type="button" class="btn btn-dark">
            <fa-icon [icon]="['fas', 'edit']"></fa-icon>
          </button>
          |
          <button type="button" class="btn btn-dark">
            <fa-icon [icon]="['fas', 'trash']"></fa-icon>
          </button>
          |
          <button
            *ngIf="video.approved; else elseBlock"
            type="button"
            class="btn btn-dark"
          >
            <fa-icon [icon]="['fas', 'check']"></fa-icon></button
          ><ng-template #elseBlock
            ><button type="button" class="btn btn-dark">
              <fa-icon [icon]="['fas', 'play']"></fa-icon></button
          ></ng-template>
        </td>
        <td>
          <span class="badge badge-success badge-pill">
            <fa-icon [icon]="['fas', 'thumbs-up']"></fa-icon>{{ video.likes }}
          </span>
        </td>
        <td>
          <span class="badge badge-primary badge-pill">
            <fa-icon [icon]="['fas', 'thumbs-down']"></fa-icon>
            {{ video.unlike }}
          </span>
        </td>
      </tr>
    </tbody>
  </table>
</div>

// lab03-react-ui/src/components/videolist/Videolist.js
import React, { Component } from "react";
import { Table } from "react-bootstrap";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import PropTypes from "prop-types";

export class Videolist extends Component {
  render() {
    return (
      <Table striped bordered hover variant="dark">
        <thead>
          <tr>
            <th scope="col">
              <button type="button" className="btn btn-dark">
                <FontAwesomeIcon icon="plus" />
              </button>
            </th>
            <th scope="col">Title</th>
            <th scope="col">URL</th>
            <th scope="col">Action</th>
            <th scope="col">Like</th>
            <th scope="col">Unlike</th>
          </tr>
        </thead>
        <tbody>
          {this.props.videos.map(video => (
            <tr key={video.id}>
              <th scope="row" className="col-sm-1">
                {video.id}
              </th>
              <td className="col-sm-3">{video.title}</td>
              <td className="col-sm-4">{video.url}</td>
              <td>
                <button
                  type="button"
                  className="btn btn-dark"
                  data-toggle="modal"
                  data-target="#updateVideoModal"
                >
                  <FontAwesomeIcon icon="edit" />
                </button>
                |
                <button type="button" className="btn btn-dark">
                  <FontAwesomeIcon icon="trash" />
                </button>
                |
                <button type="button" className="btn btn-dark">
                  {video.approved ? (
                    <FontAwesomeIcon icon="play" />
                  ) : (
                    <FontAwesomeIcon icon="check" />
                  )}
                </button>
              </td>
              <td>
                <span className="badge badge-success badge-pill">
                  <FontAwesomeIcon icon="thumbs-up" />
                  {video.likes}
                </span>
              </td>
              <td>
                <span className="badge badge-primary badge-pill">
                  <FontAwesomeIcon icon="thumbs-down" />
                  {video.unlike}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </Table>
    );
  }
}

Videolist.propTypes = {
  videos: PropTypes.array.isRequired
};

export default Videolist;
